### ISSUE TITLE
Requirement thing

### ISSUE THREAD

**Issue by Zack7292** [DaedalusGame/Heterorustichromia#1]
Hi, i think you should clearly say in you mod's description that in require Mystical mechanics and also make it so it didn't crash when it ain't in it.

here the crash: https://pastebin.com/j2SYZp59

**Comment by DaedalusGame** [comment]
![firefox_E2oQSkf3Ha](https://user-images.githubusercontent.com/9559216/74989690-76258800-5441-11ea-9719-7fc54c30f8a8.png)

**Comment by Zack7292** [comment]
yea, i've found out, but i was talking about like adding in big in your description, since not everybody use this tab or even know about this tab

**Comment by DaedalusGame** [comment]
added it as a dependency to the mod itself now so it'll scream about it instead of crashing
